# Generated by Django 4.0.3 on 2022-05-28 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_order_shoppingcartitem_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=datetime.date(2022, 5, 28), max_length=200),
            preserve_default=False,
        ),
    ]
