# Generated by Django 4.0.3 on 2022-05-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='customer_code',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
